/*
 * Webstack Flights API
 * # Introduction Mocked flights responses for an e-commerce system  # Overview This is a REST JSON API for developing new Frontend apps at Rethink  # Authentication Some endpoints require authentication. You should use the \"Authorization\" header in POST requests, containing the token received from the /login request.  # Error Codes 400 - Bad input 401 - Not logged in 404 - Not found 500 - Server error Response body will be an explanation  # Usage Saved data will be cleared after 1 hour Server is on Heroku Hobby so it sleeps most of the time
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * PurchaseTotal
 */

public class PurchaseTotal {
  @SerializedName("miles")
  private Integer miles = null;

  @SerializedName("money")
  private BigDecimal money = null;

  public PurchaseTotal miles(Integer miles) {
    this.miles = miles;
    return this;
  }

   /**
   * Get miles
   * @return miles
  **/
  @ApiModelProperty(value = "")
  public Integer getMiles() {
    return miles;
  }

  public void setMiles(Integer miles) {
    this.miles = miles;
  }

  public PurchaseTotal money(BigDecimal money) {
    this.money = money;
    return this;
  }

   /**
   * Get money
   * @return money
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMoney() {
    return money;
  }

  public void setMoney(BigDecimal money) {
    this.money = money;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseTotal purchaseTotal = (PurchaseTotal) o;
    return Objects.equals(this.miles, purchaseTotal.miles) &&
        Objects.equals(this.money, purchaseTotal.money);
  }

  @Override
  public int hashCode() {
    return Objects.hash(miles, money);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseTotal {\n");
    
    sb.append("    miles: ").append(toIndentedString(miles)).append("\n");
    sb.append("    money: ").append(toIndentedString(money)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

